---
- hosts: datacenter_host
  gather_facts: true
  become: false
  vars:
    root_base_dir: "~/app/"
    install_prereq: false
  roles:
    - name: s3downloadlatest
      base_dir: "{{root_base_dir}}"